name: ScriptRunner

#on:
 # schedule:
  #  - cron: '0 0 * * MON'

on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner      
        
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # install the python version needed
        
      - name: Install dependencies
        working-directory: ./app
        run: pip install -r requirements.txt
          
      - name: execute py script # run sj-gobierno.py to get the latest data
        working-directory: ./app
        run: python espnexporter.py
      
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update Data" -a
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
          force: true
          
     # - name: Git push
      #  run: |
       #   git push "https://${GITHUB_ACTOR}:${TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:main
        #env:
         # TOKEN: ${{ secrets.GITHUB_TOKEN }}
